blueprint:
  name: TS0042 Zigbee Remote
  description: Configure actions for TS0042
  domain: automation
  source_url: https://raw.githubusercontent.com/zpriddy/Home-Assistant/main/blueprints/ts0042_zigbee_remote.yaml
  author: Zachary Priddy
  input:
    ts0044_device:
      name: TS0042 Remote
      selector:
        device:
          filter:
            model: TS0042

    # Actions
    button_1_press:
      name: Actions for Button 1 Pressed
      default:
      selector:
        action:

    button_1_double_press:
      name: Actions for Button 1 Double Pressed
      default:
      selector:
        action:

    button_1_held:
      name: Actions for Button 1 Held
      default:
      selector:
        action:

    button_2_press:
      name: Actions for Button 2 Pressed
      default:
      selector:
        action:

    button_2_double_press:
      name: Actions for Button 2 Double Pressed
      default:
      selector:
        action:

    button_2_held:
      name: Actions for Button 2 Held
      default:
      selector:
        action:

mode: parallel
max: 10

trigger:

  # Button 1
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_1
    id: b1-1
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: button_1
    id: b1-2
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: button_1
    id: b1-h
    
    # Button 2
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_2
    id: b2-1
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: button_2
    id: b2-2
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: button_2
    id: b2-h


action:
  - choose:
      # Button 1
      - conditions:
          - condition: trigger
            id:
              - b1-1
        sequence: !input button_1_press
      - conditions:
          - condition: trigger
            id:
              - b1-2
        sequence: !input button_1_double_press
      - conditions:
          - condition: trigger
            id:
              - b1-h
        sequence: !input button_1_held
      
      # Button 2
      - conditions:
          - condition: trigger
            id:
              - b2-1
        sequence: !input button_2_press
      - conditions:
          - condition: trigger
            id:
              - b2-2
        sequence: !input button_2_double_press
      - conditions:
          - condition: trigger
            id:
              - b2-h
        sequence: !input button_2_held